FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache netcat-openbsd python3 make g++
COPY package*.json ./
COPY prisma ./prisma
RUN npm ci
COPY docker-entrypoint.sh ./
RUN chmod +x docker-entrypoint.sh
EXPOSE 3000
ENTRYPOINT ["./docker-entrypoint.sh"]
